version: '3.8'

services:
  stealthmax-substream:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PRIVATE_KEY=${PRIVATE_KEY}
      - NAMESTONE_API_KEY=${NAMESTONE_API_KEY}
      - ALCHEMY_KEY=${ALCHEMY_KEY}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/app/logs
    networks:
      - stealthmax-network

networks:
  stealthmax-network:
    driver: bridge 