version: '3.8'

services:
  substream:
    image: docker.io/dronhex/substream:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PRIVATE_KEY=${PRIVATE_KEY}
      - NAMESTONE_API_KEY=${NAMESTONE_API_KEY}
      - ALCHEMY_KEY=${ALCHEMY_KEY}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
    restart: unless-stopped
    volumes:
      - /storage/substream/logs:/app/logs
    networks:
      - stealthmax-network

networks:
  stealthmax-network:
    driver: bridge 